<?php
if (session_status() === PHP_SESSION_NONE) session_start();
define('TEMP_DIR', __DIR__ . '/temp/');
define('DOWNLOAD_DIR', __DIR__ . '/downloads/');
define('LOGS_DIR', __DIR__ . '/logs/');
define('DB_PATH', __DIR__ . '/data/scraper.db');
define('SAVE_DIR', __DIR__ . '/data/sites/');
@mkdir(TEMP_DIR, 0777, true);
@mkdir(DOWNLOAD_DIR, 0777, true);
@mkdir(LOGS_DIR, 0777, true);

define('HIDDEN_PATHS', serialize([
    '.env', '.env.example', '.env.local', '.env.prod', '.env.dev', '.env.staging',
    '.env.production', '.env.development', '.env.test', '.env.docker',
    '.git/config', '.git/HEAD', '.gitignore', '.gitattributes', '.gitmodules',
    '.svn/entries', '.svn/wc.db',
    '.htaccess', '.htpasswd', '.htgroup',
    '.DS_Store', 'Thumbs.db', 'desktop.ini',
    'wp-config.php', 'wp-config.php.bak', 'wp-config.old', 'wp-config.txt',
    'wp-config-sample.php',
    'config.php', 'config.php.bak', 'config.php.old', 'config.php.save',
    'config.inc.php', 'config.inc.php.bak',
    'configuration.php', 'configuration.php.bak',
    'database.php', 'db.php', 'db_config.php', 'db_connect.php',
    'settings.php', 'settings.json', 'settings.inc.php',
    'composer.json', 'composer.lock',
    'package.json', 'package-lock.json', 'yarn.lock', 'bun.lockb',
    'Dockerfile', 'docker-compose.yml', '.dockerignore',
    'Makefile', 'nginx.conf', 'web.config',
    'robots.txt', 'sitemap.xml', 'sitemap.xml.gz',
    'phpinfo.php', 'info.php', 'p.php', 'i.php', 'system.php',
    'test.php', 'test.html', 'testing.php', 'demo.php',
    'backup.zip', 'backup.tar.gz', 'backup.sql', 'backup.tar.bz2', 'backup.7z',
    'dump.sql', 'db.sql', 'database.sql',
    'error.log', 'access.log', 'debug.log', 'error_log',
    'api.json', 'swagger.json', 'openapi.json',
    'webpack.config.js', 'vite.config.js', 'tsconfig.json',
    '.gitlab-ci.yml', '.travis.yml',
    'credentials.json', 'secret.json', 'api-keys.json',
    'Gemfile', 'Gemfile.lock', 'Rakefile',
    'Procfile', 'cloudbuild.yaml',
    'dump.rdb', 'redis.conf', 'mongod.conf',
    '.well-known/',
    'crossdomain.xml', 'clientaccesspolicy.xml',
    'shell.php', 'cmd.php', 'exec.php', 'upload.php',
    'xmlrpc.php',
]));

define('ADMIN_PATHS', serialize([
    'admin', 'administrator', 'adminpanel', 'admincp', 'cpanel', 'cp',
    'dashboard', 'dash', 'backend', 'backoffice',
    'wp-admin', 'wp-login.php', 'wp-signup.php',
    'phpmyadmin', 'pma', 'mysqladmin', 'adminer.php', 'adminer',
    'login', 'signin', 'auth', 'authenticate',
    'panel', 'controlpanel',
    'manager', 'management', 'moderator', 'manage',
    'user/login', 'user/admin', 'user/panel',
    'superadmin', 'super_admin', 'root', 'su',
    'siteadmin', 'webadmin', 'sysadmin',
    'server-status', 'server-info',
    'console', 'terminal', 'shell',
    'crm', 'erp', 'jenkins', 'jira', 'confluence', 'gitlab',
    'kibana', 'grafana', 'prometheus', 'nagios', 'zabbix',
    'wordpress/wp-admin', 'joomla/administrator',
    'drupal/user', 'drupal/admin',
    'moodle/admin', 'moodle/login',
    'magento/admin', 'prestashop/admin',
    'opencart/admin', 'whmcs/admin',
    'plesk', 'cpanel/login', 'directadmin',
    'webmin', 'vesta', 'hestia',
    'api/', 'api/v1/', 'api/v2/', 'api/v3/',
    'graphql', 'rest', 'soap',
    'swagger', 'api-docs', 'docs',
    'oauth', 'oauth2', 'token', 'saml', 'sso',
    'register', 'signup', 'create-account',
    'forgot-password', 'reset-password',
    'profile', 'account', 'my-account',
    'settings', 'configuration', 'preferences',
    'logs', 'log', 'audit', 'reports',
    'monitoring', 'monitor', 'stats', 'statistics',
    'ajax', 'api/rest',
    'cp/', 'control/', 'mod/', 'webadmin/',
    'bb-admin/', 'acp/', 'acp.php', 'modcp/',
    'tools/', 'tool/', 'util/',
    'install/', 'install.php', 'setup/', 'setup.php',
    'upgrade/', 'update/', 'migrate/',
    'debug/', 'debug.php', 'dev/', 'development/',
    'test/', 'testing/', 'tests/', 'sandbox/',
]));

define('DATABASE_EXTS', serialize([
    '.sql', '.db', '.sqlite', '.sqlite3', '.sqlite2',
    '.mdb', '.accdb', '.mde', '.ade', '.adp',
    '.dbf', '.frm', '.myd', '.myi', '.ibd', '.ibdata',
    '.mdf', '.ldf', '.ndf', '.bak', '.trn',
    '.sql.gz', '.sql.bz2', '.sql.xz', '.sql.zst',
    '.sql.7z', '.sql.zip', '.sql.tar',
    '.bak.sql', '.backup.sql', '.dump.sql', '.sql.backup',
    '.db-shm', '.db-wal', '.db-journal',
    '.mysql', '.pgsql', '.mariadb', '.percona',
    '.bson', '.mongodb', '.rdb', '.aof',
    '.sqlitedb', '.db3', '.s3db', '.sl3',
    '.nsf', '.ntf', '.maf',
    '.gdb', '.fdb', '.fb', '.ib',
    '.h2.db', '.h2.mv.db',
    '.ldif', '.ldb', '.dcf',
    '.dacpac', '.bacpac',
    '.edb', '.idx', '.dat',
]));

define('USER_AGENTS', serialize([
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/127.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/127.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/17.5 Safari/605.1.15',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/17.6 Safari/605.1.15',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0',
    'Mozilla/5.0 (Linux; Android 14; SM-S928B) AppleWebKit/537.36 Chrome/125.0.6422.165 Mobile Safari/537.36',
    'Mozilla/5.0 (Linux; Android 14; Pixel 9 Pro) AppleWebKit/537.36 Chrome/126.0.6478.122 Mobile Safari/537.36',
    'Mozilla/5.0 (Linux; Android 14; OnePlus 12) AppleWebKit/537.36 Chrome/126.0.6478.71 Mobile Safari/537.36',
    'Mozilla/5.0 (Linux; Android 14; Galaxy S24) AppleWebKit/537.36 Chrome/127.0.6533.84 Mobile Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1) AppleWebKit/605.1.15 Version/17.5 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6) AppleWebKit/605.1.15 Version/17.6 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (iPad; CPU OS 17_5_1) AppleWebKit/605.1.15 Version/17.5 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 Chrome/126.0.0.0 Safari/537.36',
    'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
    'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
    'Mozilla/5.0 (compatible; DuckDuckBot-Https/1.1; +https://duckduckgo.com/duckduckbot)',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/127.0.0.0 Safari/537.36',
]));
